<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\application\EveTrader.Application\EveTrader.Application.csproj" />
    <ProjectReference Include="..\..\domain\EveTrader.Domain\EveTrader.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Parquet.Net" />
    <PackageReference Include="DuckDB.NET.Data.Full" />
  </ItemGroup>

</Project>
