<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\infrastructure\EveTrader.Infrastructure.Esi\EveTrader.Infrastructure.Esi.csproj" />
    <ProjectReference Include="..\..\..\src\infrastructure\EveTrader.Infrastructure.Facts\EveTrader.Infrastructure.Facts.csproj" />
  </ItemGroup>

</Project>
